services:
  - type: worker
    name: kafka-producer
    runtime: python
    plan: free 
    repo: https://github.com/ranveerverma18/spotify_data_analytics
    branch: main
    buildCommand: pip install -r spotify_backend/requirements.txt
    startCommand: python spotify_backend/producer.py
    envVars:
      - key: KAFKA_BOOTSTRAP
        value: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
      - key: KAFKA_USERNAME
        value: YBZYWVVR4ZHOM7LJ
      - key: KAFKA_PASSWORD
        value: 8AZFKxD8XSgYhYpcg25Z4yQEIVUKVLPa0+SAkW9LjNwWVVK9RJZguxluzadIbFcr
      - key: MONGODB_URI
        value: mongodb+srv://ranveerverma18:ranveer18@mongo-db-cluster.7xghnej.mongodb.net/spotify_data?retryWrites=true&w=majority
      - key: SPOTIPY_CLIENT_ID
        value: e406584407bc4d6abfbc0ed5052983e0
      - key: SPOTIPY_CLIENT_SECRET
        value: 3052c144d4d1423e9b9bcdf02d587cc5
      - key: SPOTIPY_REDIRECT_URI
        value: http://localhost:8888/callback


  - type: worker
    name: kafka-consumer
    runtime: python
    plan: free  
    repo: https://github.com/ranveerverma18/spotify_data_analytics
    branch: main
    buildCommand: pip install -r spotify_backend/requirements.txt
    startCommand: python spotify_backend/consumer.py
    envVars:
      - key: KAFKA_BOOTSTRAP
        value: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
      - key: KAFKA_SASL_MECHANISMS
        value: PLAIN
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_USERNAME
        value: YBZYWVVR4ZHOM7LJ
      - key: KAFKA_SASL_PASSWORD
        value: 8AZFKxD8XSgYhYpcg25Z4yQEIVUKVLPa0+SAkW9LjNwWVVK9RJZguxluzadIbFcr
      - key: KAFKA_GROUP_ID
        value: spotify-consumer-group
      - key: KAFKA_AUTO_OFFSET_RESET
        value: earliest
      - key: SCHEMA_REGISTRY_URL
        value: https://psrc-epk8y.australia-southeast1.gcp.confluent.cloud
      - key: SCHEMA_REGISTRY_AUTH
        value: EFMB2DEU7PLZKQMG:dcvZBcYboTVYrBRlhSxM2uSLhFSSxzZhGO87WV5NHxyAZRzUByYm7yYtwWwyQwaS
      - key: MONGO_URI
        value: mongodb+srv://ranveerverma18:ranveer18@mongo-db-cluster.7xghnej.mongodb.net/spotify_data?retryWrites=true&w=majority